### ISSUE TITLE
[Bug] [arm64] Opening Laptop from Sleep or Hibernation Breaks Workspace Numbers

### ISSUE THREAD

**Issue by JaylenIsGone** [glzr-io/zebar#102]
### Describe the bug

I am running on a Surface Pro 11 with the arm64 Windows build of Zebar with GlazeWM, and when I turn on my laptop from sleep I have to restart Zebar to get the workspace numbers to work. They stop showing the correct numbers of what workspaces are being used and become uninteractable, but the keybinds still work, so it appears that it is mostly a Zebar issue and not a GlazeWM issue.

I am aware that other people have posted similar issues, but they appear to be after a long sleep or simply leaving Zebar open for a while, and they appear to be using the x64 builds. It happens to me every time I close and open my laptop.

### Reproduction

1. Put the computer into sleep or hibernation
2. Get the computer out of sleep or hibernation

### Version number

1.8.1

**Comment by schnow265** [comment]
Hello from x64 with the same issue.

**Comment by sitko-j** [comment]
Also having this issue, Win 11 - Intel x64

**Comment by khusmann** [comment]
(also having this issue win 11 x64)

@CtByte I see a tag for the v2, but no release / installers -- did you compile from source?

**Comment by CtByte** [comment]
@khusmann yes, I did compile, but you can try [this](https://github.com/glzr-io/zebar/actions/runs/10900669218) I think (
bundle-x86_64-pc-windows-msvc)

Just to warn you again, the config is very different, but have a look at the examples folder

**Comment by khusmann** [comment]
@CtByte Thanks!

Just got v2.0 running (-x86_64-pc-windows-msvc) but unfortunately doesn't fix the issue -- after sleeping the workspace numbers stop working.

**Comment by CtByte** [comment]
@khusmann I was really hoping it would also work for arm64, I am not sure what would be the best approach to debug this.

Thank you for trying anyway.

**Comment by lars-berger** [comment]
After v2.2.1, IPC connection to GlazeWM now gets reconnected after standby or other disconnections 👍
