### ISSUE TITLE
[Bug] Zebar is misplaced and has incorrect width on UHD monitor

### ISSUE THREAD

**Issue by Astach** [glzr-io/zebar#117]
### Describe the bug

I have 2 monitors 
- on my laptop 1920 * 1200: all good
- on my external display 3840 * 2160:  the bar doesn't take the entire width and is misplaced.

_Note: this used to work fine before v2._

![Screenshot 2024-10-01 100209](https://github.com/user-attachments/assets/b43d27ed-8ae9-4f8f-b656-a2c8c8a5e2dd)

### Version number

v2.2.1

**Comment by CtByte** [comment]
Does it change if you try different monitor scaling? And would it work if you use the same scaling on both monitors?

**Comment by x807x** [comment]
> Does it change if you try different monitor scaling? And would it work if you use the same scaling on both monitors?

I have same problem when using two monitors with different scaling.
* my laptop: 2560x1600
* external monitor: 1920x1080
It looks like this on my external monitor
![image](https://github.com/user-attachments/assets/961977ab-308e-47df-81d5-a8b0baec011f)

**Comment by lars-berger** [comment]
@JonasWischeropp Just opened a PR #119 with a potential fix for this. Personally not running into this issue, so I'm not in a great spot to test this. Would y'all mind trying out the `bundle-x86_64-pc-windows-msvc` build from https://github.com/glzr-io/zebar/actions/runs/11124709036? @Astach @x807x @gpbenton

**Comment by Astach** [comment]
I tried #119,  it does improve things.
the bar is well placed but dimensions are incorrect (too long/wide)

You can see that the time isn't centered (which is supposed to be) and that the window overlaps the bar.
![image](https://github.com/user-attachments/assets/2cfbd784-a8a9-4cc9-9967-d74aa4106f18)

Happy to help further

**Comment by s0nspark** [comment]
For me this is definitely related to having different scaling on my two displays. When I set both to use the same scaling zebar is placed and sized properly.

**Comment by lars-berger** [comment]
Fixed now in the latest v2.3.0 release 🙌 Thanks for all the help testing this
