### ISSUE TITLE
[Feature Request] Add acrylic background option for Windows or backdrop blur options.

### ISSUE THREAD

**Issue by DonHeidi** [glzr-io/zebar#123]
### Describe the problem/motivation
Great work so far! 

#### User Story

As a user, I want to either set 'Acrylic' as an option for the backdrop or use a value to set a blur, so that I have a more aligned look and feel on Windows.

I am using GlazeWM since yesterday to have tiling on my Windows machine, and today I started playing around with the configuration for the zebar widget that starts when running GlazeWM. I switched the configuration for the transparency but unfortunately, I found no way to blur it. It would be nice to create a native Windows look by applying the "Acrylic" effect.

Btw, this is my first Github issue that I open that is not work related. Feel free to feedback.

##### Current behaviour:

**The zebra bar with transparent background**
![image](https://github.com/user-attachments/assets/61cfbf8c-de5e-40cb-824a-c5204591e3fd)

**The Windows taskbar (dark mode):**

![image](https://github.com/user-attachments/assets/7f55f88e-018d-4bca-a80a-2f58faf0c0ed)

##### Desired Behaviour:

Zebar widget has the same background as the taskbar.

#### Considered solutions

I have tried to control this with CSS (background: rgba(0,0,0,0/5); backdrop-filter: blur(40px) but as the image is not part of the background of the web view, this has no effect.

#### Possible solution:

I stumbled upon this package:
[https://github.com/tauri-apps/window-vibrancy](https://github.com/tauri-apps/window-vibrancy)

As I am not well versed with Rust or Tauri, I can't say, if this was a good drop in solution but it could be a good start even if it does not support Linux.

##### Describe the solution you'd like

I want to either set 'Acrylic' as an option for the backdrop or use a value to set a blur, so that I have a more aligned look and feel with the Windows taskbar and other Windows Applications.

##### Alternatives considered

I have tried to manipulate the background with CSS.

I found this repo: [https://github.com/tauri-apps/window-vibrancy](https://github.com/tauri-apps/window-vibrancy)

**Comment by lars-berger** [comment]
Hey @DonHeidi, thanks for the well-written feature request 👍 We already have a similar request at #93 - will close this one so we don't end up with duplicates and can keep the discussion in one place.

**Comment by DonHeidi** [comment]
Sure! I have overlooked the issue.

**Comment by lars-berger** [comment]
> 🎉 This issue has been resolved in version 2.4.0 🎉
> 
> The release is available on:
> 
> * [npm package (@latest dist-tag)](https://www.npmjs.com/package/zebar/v/2.4.0)
> * [GitHub release](https://github.com/glzr-io/zebar/releases/tag/untagged-bfc4d7b333b08d90d1cd)
> 
> Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot 📦🚀

Bot incorrectly marked as resolved 🤔 - no connected PR's and not assigned yet
