### ISSUE TITLE
[Bug] After uninstallation I still see zebar taskbars

### ISSUE THREAD

**Issue by maku** [glzr-io/zebar#148]
### Describe the bug

After uninstalling zebar, I still see the zebar taskbar at the top of the screen on 2 out of 3 screens. What can I do there?

### Version number

2.3.0 (I guess)

**Comment by lars-berger** [comment]
Maybe you have a duplicate scoop or winget install of Zebar? In CMD, try running `which zebar` to locate where it might still be installed

Closing as it's likely not a Zebar-specific issue
