### ISSUE TITLE
[Bug] Audio provider not working

### ISSUE THREAD

**Issue by Ajay-056** [glzr-io/zebar#169]
### Describe the bug

Im using Windows and trying to add the audio volume in the zebar, As a first step have added the provider in createProviderGroup.

      const providers = zebar.createProviderGroup({
        network: { type: 'network', refreshInterval: '2000'},
        glazewm: { type: 'glazewm' },
        cpu: { type: 'cpu', refreshInterval: '2000' },
        date: { type: 'date', formatting: 'EEE	dd MMM hh:mm:ss a' },
        battery: { type: 'battery', refreshInterval: '2000'},
        memory: { type: 'memory', refreshInterval: '2000'},
        weather: { type: 'weather' },
        host: { type: 'host', refreshInterval: '5000'},
        ip: { type: 'ip' },
        disk: { type: 'disk', refreshInterval: '15000' },
        audio: { type: 'audio' },
      });

**Usage:**      
`
              {output.audio && (
                <div className="audio">
                  {output.audio.playbackDevice.name}
                </div>
              )}
`

**Outcome:** (Zebar was blank)
![image](https://github.com/user-attachments/assets/673b2507-0d42-4f9a-85cb-4b811da4484b)

### Reproduction

Add the audio provider in createProviderGroup and refresh zebar.

      const providers = zebar.createProviderGroup({
        network: { type: 'network', refreshInterval: '2000'},
        glazewm: { type: 'glazewm' },
        cpu: { type: 'cpu', refreshInterval: '2000' },
        date: { type: 'date', formatting: 'EEE	dd MMM hh:mm:ss a' },
        battery: { type: 'battery', refreshInterval: '2000'},
        memory: { type: 'memory', refreshInterval: '2000'},
        weather: { type: 'weather' },
        host: { type: 'host', refreshInterval: '5000'},
        ip: { type: 'ip' },
        disk: { type: 'disk', refreshInterval: '15000' },
        audio: { type: 'audio' },
      });

### Version number

2.5.1

**Comment by lars-berger** [comment]
Audio provider is in `main` but hasn't been put out in a new release just yet.

Just merged in another feature for the `audio` provider so the volume can be changed now 👌 #170. A new release with the new stuff will be out in the next few days.

**Comment by Ajay-056** [comment]
the provider documentation was present in the readme, hence gave it a try, my bad 🙂 excited to use it in a few days 🎉
