### ISSUE TITLE
[Bug] Displaying GlazeWM workspaces is not working.

### ISSUE THREAD

**Issue by vapmKK** [glzr-io/zebar#172]
### Describe the bug

Displaying GlazeWM workspaces is not working.

### Reproduction

After updating to the latest version of Zebar (2.6.0) and GlazeWM (3.6.0), the GlazeWM workspaces are not showing up at all. After inspecting the widget The only error in the consoles is this:
<img width="941" alt="msedgewebview2_Nfl6JBIPHG" src="https://github.com/user-attachments/assets/1dab500b-c0bb-456a-8cbc-28665920e6fe">

Pointing to the createGlazeWmProvider function.

### Version number

2.6.0

**Comment by dillacorn** [comment]
I just started experiencing this...

**Comment by n-crespo** [comment]
Also started experiencing this... makes glazewm unusable for me. Issue may be related to [#870](https://github.com/glzr-io/glazewm/pull/870).

**Comment by MoaidHathot** [comment]
I also just experienced this. What has changed? I didn't update my GlazeWM or Zebar version for a while

**Comment by dillacorn** [comment]
I'm using Zebar version 2.5.1 from chocolatey and this started happening to me... So I'm just as confused as everyone else.

**Comment by MoaidHathot** [comment]
At the discord server people says it might be related to a CDN issue, although I can't see any networking issues with Zebar (inspect)

**Comment by dillacorn** [comment]
OK more reason I dislike this bar on top of how unnecessarily complicated it seems to setup/configure.. Are there alternatives for Windows? At this rate I may as well look into getting Polybar with WSL2 working.. I also don't like that it's clearly based on Chromium.

**Comment by alxcasta13** [comment]
Hello.
Has anyone found a solution to this problem?
Perhaps temporary fixes or alternative options could be explored while working toward a permanent solution.

**Comment by dillacorn** [comment]
> Has anyone found a solution to this problem?

Based on the discord post about the same issue a user is saying you can create a config that doesn't utilize a URL link for some assets.. I'm personally still looking into this but def want to find a fix for myself.. I'd prefer if Zebar didn't require the internet for anything.

**Comment by MoaidHathot** [comment]
What asset is that? Nerdfonts?

**Comment by blurm** [comment]
Same problem from yestoday. glazewm in output is null. Can we just use local asset?

**Comment by dillacorn** [comment]
> What asset is that?
Couldn't tell ya.. The user stating that hasn't provided his configuration files...

If I find a solution I'll report back. Otherwise there should be someone eventually to find a permanent solution.

**Comment by x807x** [comment]
I just found a temporary fix.
By changing 
```
import * as zebar from 'https://esm.sh/zebar@2';
```
to
```
import * as zebar from 'https://esm.sh/zebar@2.5.1';
```
in my configuration
It seems like there's some bug in zebar@2.6.0

**Comment by dillacorn** [comment]
Confirmed working @x807x !

**Comment by qwavies** [comment]
its line 29 for me but @x807x 's fix does work 
ty for the fix 👍 

and yes ideally I also agree with the sentiment that zebar should be able to function without any internet connection

**Comment by SebasF1349** [comment]
Just to clear some misconceptions: Zebar works without internet connection. The premade bar that is shipped as an example uses internet to make it easier to non-developers, but you can 100% create a custom bar that doesn't use internet. You can find many examples in GlazeWM discord.

There is a GitHub issue where it is being tracked the idea to ship a premade that doesn't need internet: https://github.com/glzr-io/zebar/issues/130

**Comment by data-miner00** [comment]
I am also experiencing this today

**Comment by lars-berger** [comment]
Fix is live now, sorry about the downtime with this!

Also thanks so much @SebasF1349 for pointing people to a temp fix in the meantime 🙏
