### ISSUE TITLE
Start as a service?

### ISSUE THREAD

**Issue by melMass** [glzr-io/zebar#28]
I've been looking for such a projects for a long time (I tried various alternatives and currently use rainmeter which I'm not a fan of). Thanks for that.

I mainly use a mac an a windows PC but I never understood services on the later, I know how to use LaunchAgent etc on mac and it works fine, what would be the alternative on windows to setup the bat file as a service? Is there some idiomatic way?

Thanks

**Comment by lars-berger** [comment]
@melMass Are you looking to get it running on system start? If so, you can move the `start.bat` script to `C:\Users\<YOUR_USER>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`.
