### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by gldtn** [glzr-io/zebar#33]
Has anyone tried using it on macOS yet? I installed the latest release, but I'm a little lost on how it works as nothing shows up when I run zebar. If I try to run from command line:

```
/Applications/Zebar.app/Contents/MacOS/Zebar open bar
```

I get an error saying that the width in config isn't valid. Number must be greater than or equal to 1..

I'm guessing from this line in the config `width: '{{ self.args.MONITOR_WIDTH }}'`

**Comment by lars-berger** [comment]
My bad, forgot to add start scripts to the latest release - [they've been added now](https://github.com/glzr-io/zebar/releases/tag/v1.3.0). The contents of `start.sh` looks like this:
```sh
#!/usr/bin/env bash
# Run `zebar open bar --args ...` for every monitor.
zebar monitors --print0 | xargs -0 -P 99 -I % sh -c 'zebar open bar --args %'
```
So if zebar is not in your PATH, change it to point to `/Applications/Zebar.app/Contents/MacOS/Zebar`

**Comment by gldtn** [comment]
> My bad, forgot to add start scripts to the latest release - [they've been added now](https://github.com/glzr-io/zebar/releases/tag/v1.3.0). The contents of `start.sh` looks like this:
> 
> ```shell
> #!/usr/bin/env bash
> # Run `zebar open bar --args ...` for every monitor.
> zebar monitors --print0 | xargs -0 -P 99 -I % sh -c 'zebar open bar --args %'
> ```
> 
> So if zebar is not in your PATH, change it to point to `/Applications/Zebar.app/Contents/MacOS/Zebar`

Awesome that worked, I'll play with it throughout the week. Thanks for sharing!
