### ISSUE TITLE
Question: Can I switch workspaces via buttons on bar?

### ISSUE THREAD

**Issue by thearturca** [glzr-io/zebar#42]
I wanna do something like that.
Is that possible?

```TS
<button onClick={{() => komorebi.currentMonitor.focusWorkspace(workspace.name)}}>
{{ workspace.name }}
</button>
```

**Comment by lars-berger** [comment]
Not just yet. Currently there isn't a way to add event handlers (eg. click, mouse over, etc) in Zebar. I'm actively working on getting this added soon though.

**Comment by lars-berger** [comment]
Added scripting support in the v1.6 release from a while back 👍 [Latest release](https://github.com/glzr-io/zebar/releases)
