### ISSUE TITLE
Question: Komorebi Workspace Icons per monitor?

### ISSUE THREAD

**Issue by eric-dishman-ctct** [glzr-io/zebar#45]
Hi, thanks for creating Zebar, I really like it so far. 

I have two monitors and when I switch workspaces, I notice that the active workspace changes on both monitors. Is it possible to configure Zebar different per monitor? 

Thanks.

**Comment by lars-berger** [comment]
Separate workspaces correctly display on multi-monitor setups now with the `glazewm` and `komorebi` providers 👍 [Latest release](https://github.com/glzr-io/zebar/releases)
