### ISSUE TITLE
Question: Is there a way to reserve space for Zebar when using Komorebi?

### ISSUE THREAD

**Issue by pluque01** [glzr-io/zebar#50]
I would like to have some space reserved for zebar. Right now the bar overlaps with my other windows when using Komorebi.

This is what I have:
![image](https://github.com/glzr-io/zebar/assets/45895450/f492a9da-62bd-4d1e-8c07-a70115db8897)

**Comment by CtByte** [comment]
Hi @pluque01 

This [video](https://youtu.be/iaZWBmVzd0A?si=3Rc6rlE12ZjY0zLQ&t=579) should be helpful.

I have 2 monitors so I use the global setting instead:

`"global_work_area_offset":
  {
	"bottom": 35,
	"left": 0,
	"right": 0,
	"top": 35
  },`

**Comment by pluque01** [comment]
Thank you so much @CtByte, I was unaware of that option in komorebi. For know it works great, but I will have to check how it works with my second monitor

**Comment by azinsharaf** [comment]
@pluque01 what version of komorebi are you using? I've upgraded mine to `0.1.24` and now zebar can't show the workspaces.
![image](https://github.com/glzr-io/zebar/assets/10101468/44eaf564-85a1-47f5-9610-33eace7b8f4a)

**Comment by CtByte** [comment]
Hi @azinsharaf 

if I may, I think in general it is good practice to use the version of Komorebi that is currently being used by Zebar, which is `0.1.23`. That may solve your issue, but I am not sure. It can also be caused by something invalid in your Zebar config.

You can build Zebar from source as well, if you want, and update the Komorebi version. I am doing that myself and the generated .msi by default has the version 0.0.0. That can be related to your other issue #51 

Hope this helps

**Comment by azinsharaf** [comment]
> Hi @azinsharaf
> 
> if I may, I think in general it is good practice to use the version of Komorebi that is currently being used by Zebar, which is `0.1.23`. That may solve your issue, but I am not sure. It can also be caused by something invalid in your Zebar config.
> 
> You can build Zebar from source as well, if you want, and update the Komorebi version. I am doing that myself and the generated .msi by default has the version 0.0.0. That can be related to your other issue #51
> 
> Hope this helps

thanks, it had the same issue with komorebi `0.1.23` as well. but i agree regarding the use of a version that is currently being used, in zebar. 
i will check the zebar config more.

**Comment by pluque01** [comment]
> @pluque01 as a different topic, what version of komorebi are you using? I've upgraded mine to `0.1.24` and now zebar can't show the workspaces. ![image](https://private-user-images.githubusercontent.com/10101468/321363254-44eaf564-85a1-47f5-9610-33eace7b8f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjgzNDAsIm5iZiI6MTcxMjgyODA0MCwicGF0aCI6Ii8xMDEwMTQ2OC8zMjEzNjMyNTQtNDRlYWY1NjQtODVhMS00N2Y1LTk2MTAtMzNlYWNlN2I4ZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA5MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTliNWYzMzNjN2Y3YWYxYzEwZWYwOTNkOGRmYjQwZjVlMTgyMjBhMmY1ZWE3YmI1MDc5YmRkNWRjZTNhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ozphpcIG7wde-UgueOEgYjmx71-QbJRR2UcUTPWHCFY)

Hi @azinsharaf.
Yesterday I upgraded komorebi from `0.1.22` to `0.1.24` and the same thing happened to me. Let me know if you find a solution, I will do the same :)

**Comment by azinsharaf** [comment]
> > @pluque01 as a different topic, what version of komorebi are you using? I've upgraded mine to `0.1.24` and now zebar can't show the workspaces. ![image](https://private-user-images.githubusercontent.com/10101468/321363254-44eaf564-85a1-47f5-9610-33eace7b8f4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MjgzNDAsIm5iZiI6MTcxMjgyODA0MCwicGF0aCI6Ii8xMDEwMTQ2OC8zMjEzNjMyNTQtNDRlYWY1NjQtODVhMS00N2Y1LTk2MTAtMzNlYWNlN2I4ZjRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDA5MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOTliNWYzMzNjN2Y3YWYxYzEwZWYwOTNkOGRmYjQwZjVlMTgyMjBhMmY1ZWE3YmI1MDc5YmRkNWRjZTNhZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ozphpcIG7wde-UgueOEgYjmx71-QbJRR2UcUTPWHCFY)
> 
> Hi @azinsharaf. Yesterday I upgraded komorebi from `0.1.22` to `0.1.24` and the same thing happened to me. Let me know if you find a solution, I will do the same :)

thanks for checking. i will submit a seperate issue for this.
