### ISSUE TITLE
Focus Workspace GlazeWM

### ISSUE THREAD

**Issue by pex81** [glzr-io/zebar#56]
`

      template/glazewm:
        styles: |
          display: flex;
          align-items: center;

          .workspace {
            background: rgba(44, 122, 254, 1);
            margin-right: 4px;
            width: 30px;
            height: 30px;
            color: #ffffffe6;
            border: none;
            border-radius: 2px;
              
          }   
        providers: ['glazewm']
        template: |
          @for (workspace of glazewm.workspacesOnMonitor) {
            <button class="workspace">
              {{ workspace.name }}
            </button>
          }  
`
How can I highlight the workspace in use in different colors? 
and is it possible to click on the workspace number to change workspace?

![immagine](https://github.com/glzr-io/zebar/assets/58252398/a8581888-b209-4ae2-9e6f-555cd442efe5)

**Comment by zennolux** [comment]
That's exactly what I want to ask

**Comment by lars-berger** [comment]
This has been added to the sample config 👍 [Latest release](https://github.com/glzr-io/zebar/releases)

**Comment by zennolux** [comment]
You are great!
