### ISSUE TITLE
[Bug] Error adding Zebar to winget

### ISSUE THREAD

**Issue by 2gn** [glzr-io/zebar#63]
I'm trying to add Zebar to [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository, but the maintainer says that the package version does not match.

See: https://github.com/microsoft/winget-pkgs/pull/160828#pullrequestreview-2151999310

Edit: I searched for "0.0.0" in this repository and found several files. Maybe these should be replaced by "1.3.0".

https://github.com/search?q=repo%3Aglzr-io%2Fzebar%200.0.0&type=code

**Comment by lars-berger** [comment]
Likely due to #51

**Comment by michidk** [comment]
zebar is now available on winget: 
https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/glzr-io/zebar/1.8.1

**Comment by MoaidHathot** [comment]
We should also automate this via the Winget Releaser

**Comment by michidk** [comment]
I automated it in my winget repo for now: https://github.com/michidk/winget/blob/main/.github/workflows/update-packages.yml#L29

But of course, we could setup a action here as well

**Comment by MoaidHathot** [comment]
@michidk,  yeah, I think the action should be part of this repo. It is more maintainable and transparent that way.

**Comment by 2gn** [comment]
I'll close this issue since the main problem is resolved. Thank you!
