### ISSUE TITLE
[Bug] `RunError: Failed to initialize window` error (installed Zebar through scoop)

### ISSUE THREAD

**Issue by KT-Prajwal** [glzr-io/zebar#66]
# Environment:
Windows 10 `(Minor: 0; Build: 19045; Revision: 0)`

# Setup
- Followed the steps in #37 to install through scoop (**Why?** : Had to install it without `admin` rights)
```shell
> scoop bucket add mtb https://github.com/melMass/scoop-mtb.git
> scoop install zebar
```
- Installed `zebar` successfully. 

# Test
- `zebar` works properly in powershell
```shell
> zebar monitors
MONITOR_NAME="\\.\DISPLAY1" MONITOR_X="0" MONITOR_Y="0" MONITOR_WIDTH="2560" MONITOR_HEIGHT="1440" MONITOR_SCALE_FACTOR="1"
```

# Issue
- Running `start.bat` throws the error:

> **Failed to initialize window!**
> **Problem reading config file. Command 'read_config_file' failed: "Unable to write to C:\\Users\\USER\\.glzr/zebar\\config.yaml"**

## Shell Status
![image](https://github.com/user-attachments/assets/e89b82d4-1810-4592-bcd2-255421a6528c)

## Error Notification
![image](https://github.com/user-attachments/assets/530fded7-7fdd-485c-aa7d-c44601ff4b08)

**Comment by lars-berger** [comment]
When launching the window, it's recognizing your home directory as `C:\\Users\\40108353` which is probably not correct. We use the `home` crate for getting the user home directory.

>Returns the value of the USERPROFILE environment variable if it is set and it is not an empty string. Otherwise, it tries to determine the home directory by invoking the [SHGetKnownFolderPath](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath) function with [FOLDERID_Profile](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid).
>
> https://docs.rs/home/0.5.9/home/fn.home_dir.html#windows

So it seems like installing through Scoop is causing the `USERPROFILE` env variable to be set to a weird value. Perhaps it'd best for us to directly call `SHGetKnownFolderPath` instead.

**Comment by lars-berger** [comment]
No longer an issue in V2+ 👍
