### ISSUE TITLE
[Feature Request] Reserve screen space via appbar API

### ISSUE THREAD

**Issue by rp1231** [glzr-io/zebar#68]
There is this another bar app called yasb which automatically reserves screen space for the bar so that the windows resize and are not overlapped by the bar.
I'm using zebar with komorebi, and it doesn't do that. 
It would be great if this could be added. 
Thanks

**Comment by lars-berger** [comment]
This can be done via the appbar win32 API (e.g. `SHAppBarMessage`) 👍 As mentioned, [yasb's implementation](https://github.com/da-rth/yasb/blob/tauri-port/src-tauri/src/win32/app_bar.rs) is a good reference for how to get this working
