### ISSUE TITLE
[Feature Request] Missing providers

### ISSUE THREAD

**Issue by aleDsz** [glzr-io/zebar#71]
I've looked through the code and docs but couldn't find some providers that we had using the older GlazeWM version like:

- `window title`
- `music`
- `gpu`
- `volume`

**Comment by lars-berger** [comment]
We've got an open issue for a media/music provider at #73. These are pretty big features so could you instead open separate issues for these? That way we could separately draft and discuss what variables we'd want to expose via these new providers
