### ISSUE TITLE
[Feature Request] Make Nerd Font icons available offline instead of fetching them

### ISSUE THREAD

**Issue by AfzGit** [glzr-io/zebar#77]
There are many problems that occur with an online approach:

**Problem Case 1:** You are outside without an internet connection, Zebar will not load it's icons
**Problem Case 2:** Your system is slow to connect to Wi-Fi which causes Zebar to start on launch without icons
**Problem Case 3:** Your Wi-Fi is slow/unresponsive, leaving you with no icons in Zebar (happens a lot with me)
**Problem Case 4:** Site is unresponsive
**Problem Case 5:** File is moved/removed from Nerdfonts site
**Problem Case 6:** File is updated and class names can change, making previous use of classes in Zebar do nothing

Consider adding `webfont.css` file (600kb size) to the project for offline use to solve all the problems above. Offline use does not seem to be breaking any licenses.

---
Code to change: 
```yaml
# Consider fetching this offline
window/bar:
    global_styles: |
        @import "https://www.nerdfonts.com/assets/css/webfont.css";
```
---
- No icons Without Wi-Fi:
  - ![image](https://github.com/user-attachments/assets/cb69be06-980a-4ea8-bc71-a04dc06ee99e)
- With Wi-Fi:
  - ![image](https://github.com/user-attachments/assets/1a2c345b-6031-412b-9c54-97f0e6e46e94)

**Comment by CtByte** [comment]
I imagine that the option is there so you can decide to use any font you want, but perhaps having the option to import from a local file would be a good alternative

```yaml
window/bar:
    global_styles: |
        @import "./assets/css/webfont.css";
```

**Comment by AfzGit** [comment]
> I imagine that the option is there so you can decide to use any font you want, but perhaps having the option to import from a local file would be a good alternative
> 
> ```yaml
> window/bar:
>     global_styles: |
>         @import "./assets/css/webfont.css";
> ```

Importing this way does not work. I reported this issue after trying to import it offline like you have shown
> config: ![image](https://github.com/user-attachments/assets/2d10f702-31e5-4f87-9d90-5562df3f041f)

**Comment by CtByte** [comment]
@AfzGit Yes, I was not sure if this would work and by the looks of it, tauri needs to do this a bit differently, just like how to `config.yaml` and `script.js` is loaded. I am not that familiar with tauri apps, but being able to load/import styles like that ( `./webfonts.css` ) would be pretty useful as you pointed out.

I tried to load directly, but I was not really expecting that to work 😆 

![image](https://github.com/user-attachments/assets/a9e57c56-8fab-4b6d-9f35-a7ae3a71cdf3)

**Comment by edelvarden** [comment]
@AfzGit , @CtByte 

![image](https://github.com/user-attachments/assets/f2d14201-5783-4bf3-a510-b5d8731d57a9)
![image](https://github.com/user-attachments/assets/14ebd1e7-33a6-4b19-b56d-bf3e0128886a)


## Step 1: Download Resources
1. [Download `webfont.css`](https://www.nerdfonts.com/assets/css/webfont.css)
2. [Download `Symbols-2048-em Nerd Font Complete.woff2`](https://www.nerdfonts.com/assets//fonts/Symbols-2048-em%20Nerd%20Font%20Complete.woff2)

## Step 2: Prepare the Font File

1. Rename the downloaded `.woff2` file to `font.woff2`.
2. Move `font.woff2` to the `zebar` folder located at `C:\Users\<USER NAME>\.glzr\zebar`.

Here’s what your directory should look like:
```
    Directory: C:\Users\<USER NAME>\.glzr\zebar


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         8/12/2024   2:26 PM           7886 config.yaml
-a----         8/12/2024   2:22 PM         963444 font.woff2
-a----         8/12/2024   2:04 PM            185 script.js
-a----          8/3/2024   7:24 PM            320 start.bat
-a----         8/12/2024   2:28 PM         471732 webfont.css
```

## Step 3: Update `webfont.css` and `config.yaml`

1. Replace `<USER NAME>` in the file paths with your  user name.
2. Open `webfont.css` and replace the existing font URL:

    Replace: `url("../fonts/Symbols-2048-em Nerd Font Complete.woff2")` 
    
    With:  `url("http://asset.localhost/C%3A%5CUsers%5C<USER NAME>%5C.glzr%5Czebar%5Cfont.woff2")`.

webfont.css
```css
/*
 *# [Nerd Fonts]  Website: https://www.nerdfonts.com
 *# [Nerd Fonts]  Development Website: https://github.com/ryanoasis/nerd-fonts
 *# [Nerd Fonts]  Version: 3.2.1
 *# [Nerd Fonts]  The following is generated from the build script
 */
@font-face{font-family:'NerdFontsSymbols Nerd Font';src:url("http://asset.localhost/C%3A%5CUsers%5C<USER NAME>%5C.glzr%5Czebar%5Cfont.woff2")
...
```
3. In `config.yaml`, update the `global_styles` section:

config.yaml
```yaml
...
  global_styles: |
    @import "http://asset.localhost/C%3A%5CUsers%5C<USER NAME>%5C.glzr%5Czebar%5Cwebfont.css";
...
```

**Comment by CtByte** [comment]
@edelvarden This is so well written, you should make a PR. Thank you very much!

**Comment by hongyuanjia** [comment]
I am trying to migrate to Glazewm v3. I am not familiar with CSS and JS. Can I directly use the name of the locally installed Nerd font on Windows instead of specifying the full path of the font file?

**Comment by CtByte** [comment]
@hongyuanjia I installed "JetBrains Mono" font on Windows and use it in the CSS like this:

```yaml
  styles: |
    display: grid;
    grid-template-columns: 1fr 1fr 1fr;
    align-items: center;
    height: 100%;
    font-family: "JetBrains Mono", ui-monospace, monospace;
    font-size: 14px;
```

So, I think if you installed the Nerd font then you can use it by name instead of the url to the `woff2` file in the `webfont.css`. I hope that is what you meant.

**Comment by hongyuanjia** [comment]
@CtByte Yes, that's exactly what I want. I just remembered that I needed to quote the font names. Thanks!

**Comment by lars-berger** [comment]
Closing in favor of #130
