### ISSUE TITLE
[Feature Request] Add a faq recommending to update webview2

### ISSUE THREAD

**Issue by ayaOwO** [glzr-io/zebar#79]
I've heard a couple of people in the discord having trouble getting zebar to work.

I also had a hard time. In all the cases I've seen the solution was to update webview2 and run the installer as administrator. 

The error message isn't very intuitive and if you run The installer without admin privileges it will just tell you webview2 is already installed.

**Comment by lars-berger** [comment]
Thanks for the heads up - added an [faq section to the readme](https://github.com/glzr-io/zebar?tab=readme-ov-file#-faq)
