### ISSUE TITLE
[Bug] Zebar freezes after Windows sleep

### ISSUE THREAD

**Issue by irosyadi** [glzr-io/zebar#86]
### Describe the bug

Zebar freezes after Windows 10 sleep. The time widget updates correctly, but the other widgets are frozen and not updating. We need to run the start.bat file to restart Zebar.

### Reproduction

1. Start Zebar
2. Put Windows to sleep

### Version number

1.8.1

**Comment by lars-berger** [comment]
Duplicate of #54

Is this with the `komorebi` or `glazewm` provider btw?

**Comment by irosyadi** [comment]
> Duplicate of #54
> 
> Is this with the `komorebi` or `glazewm` provider btw?

glazewm
