### ISSUE TITLE
[Bug] Workspace buttons unresponsive

### ISSUE THREAD

**Issue by jacobduijzer** [glzr-io/zebar#87]
### Describe the bug

I am using zebar, on a dual-monitor setup (together with Glaze-wm). Both bars are working, I can switch workspaces by clicking (or by using the keyboard), but after a while clicking doesn't work anymore. Switching by using keyboard shortcuts still works. I can right-click on the bar, refresh the bar and it will work again, but only for a while. 

The inspect window console shows an event: 'Focus button clicked!', but my workspace doesn't change. I don't see any errors, as far as I know.

### Version number

zebar -V shows 0.0.0 but I installed v1.8.1 from GitHub

**Comment by CtByte** [comment]
@jacobduijzer It seems to me that this is related to this issue https://github.com/glzr-io/zebar/issues/54

Both the Komorebi and Glaze providers freeze up after some time.

**Comment by CtByte** [comment]
@jacobduijzer Try the v2 that was recently released. I've been using it for a while and the freezing issue is gone

**Comment by jacobduijzer** [comment]
> @jacobduijzer Try the v2 that was recently released. I've been using it for a while and the freezing issue is gone

I don't see a v2 release? Only a v2.0.0 tagged source code package. Did you build v2 yourself?

**Comment by CtByte** [comment]
I did, but it should be in the main branch

what if you try [this](https://github.com/glzr-io/zebar/actions/runs/10900669218)

**Comment by jacobduijzer** [comment]
I installed the new v2.0.0 version, still same issue. I refresh my bar(s), they will be responsive for a while, but freezing quickly, which means I can't see active workspaces indicator changing, nor can't I click on any workspace to switch.

**Comment by khusmann** [comment]
@jacobduijzer I also had the same experience with v2.0.0. But just installed v2.1.1 (just released), and it seems to be working now!

**Comment by jacobduijzer** [comment]
I installed v2.2.1 this morning, after a day of working, it seems to work fine! I will close this issue, thanks!
