### ISSUE TITLE
[Feature Request] Want a config reload feature or hotkey

### ISSUE THREAD

**Issue by Gilmour-99** [glzr-io/zebar#94]
### Describe the problem/motivation

When i change config of my zebar for glazewm, the only way is to shutdown and then reboot glazewm and zebar simutaneously. 
However glazewm has the hotkey shift+alt+R to reload the config which is really conveinet for us to config glazewm.

### Describe the solution you'd like

So, how about add this feature to zebar, by just  use the same hotkey we can reload the zebar and glazewm simultaneously, and that can let us cofig glazewm and zebar in double efficient.

**Comment by earthpwn** [comment]
Right click menu of the zebar has Refresh option. Could you please give it a try? Not sure if it doing full config refresh or only visual html & css

**Comment by Gilmour-99** [comment]
Thanks, and that works right for me, but i'm not sure about its behaviour too.

**Comment by lars-berger** [comment]
A config reload option via the system tray has been added in v2.2.1+ 👍
