### ISSUE TITLE
[Bug] On Monitor switch via KVM switch, the bars aren't shown

### ISSUE THREAD

**Issue by SoraTenshi** [glzr-io/zebar#95]
### Describe the bug

All the Monitors don't show the Bars on each Monitor, but at best only 1 (usually at max 75% of the width)

I would expect Zebar to sort of restores itself.

(Also interestingly, `zebar -V` only shows the version 0.0.0)

### Reproduction

1. Start Zebar
2. Remove all monitors from the Input source, e.g. via KVM switch or just disconnecting them from the computer
3. Leave them disconnected for ~1-2 Minutes
4. Reconnect them / switch the KVM switch

### Version number

0.0.0 (5th August 2024)

**Comment by SoraTenshi** [comment]
Updating fixed it apparently.

**Comment by lars-berger** [comment]
After the v2.2.1 release, monitor connections/disconnections should be handled correctly now 👌 

There still seems to be an issue with window positioning on scaled monitors, which is tracked here #117
