### ISSUE TITLE
[Bug] netsh's output is localized and causes missing SSID & signal strength on non-English systems

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [glzr-io/zebar#96]
### Describe the bug

Exactly what the title says. Zebar uses a simple regex over a netsh output to obtain signal information, but netsh output is localized for the language that the system is set to, and has no option to de-localize it.

Use a windows API instead.

### Reproduction

Set your system to any language other than English, like Spanish.

### Version number

i don't know, zebar --version doesn't work

**Comment by lars-berger** [comment]
Tried to reproduce this by changing my system language but `netsh wlan show interfaces` continues to output the same. Would you mind posting a log or screenshot of the CLI output from `netsh wlan show interfaces`? (strip out any personal details if you need to)

If it can reliably be parsed through `netsh`, then we might not have to turn to Windows APIs

**Comment by Lilith-In-Starlight** [comment]
Yes, here it is
![image](https://github.com/user-attachments/assets/2ea47ac6-646f-4d4b-b915-cfeaac2539e8)

**Comment by lars-berger** [comment]
> Yes, here it is. The spanish word for "signal" is "señal"
> 
> ![image](https://private-user-images.githubusercontent.com/56773311/367902110-2ea47ac6-646f-4d4b-b915-cfeaac2539e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3ODM4NTksIm5iZiI6MTcyNzc4MzU1OSwicGF0aCI6Ii81Njc3MzMxMS8zNjc5MDIxMTAtMmVhNDdhYzYtNjQ2Zi00ZDRiLWI5MTUtY2ZlYWFjMjUzOWU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDExNTIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZjA0Njc5ZGE1YzRiNDY2NDY0OGIzNmI2OTJiZDFiMjg2ZGVjNmQxNjliZmIxZDJjZTRkNzE0YTg2NGVmZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nDtsk1IBtLN0wXXZdHzDoSytW36ZXdRD9_JHbJTh9Vs)

Yeah that doesn't look ideal to parse. We should use something else

Changed it in v2.2.1 so that it no longer panics, but the underlying problem is still there
