### ISSUE TITLE
[Bug] Zebar dont open on Windows 11

### ISSUE THREAD

**Issue by JimmyXD2** [glzr-io/zebar#98]
### Describe the bug

I downloaded the latest version of the .msi file for Windows (not Arm), when I open it, it only flashes the terminal but does not open the Zebar program, it does not even show up in the task manager.

OS version: Windows 11 Enterprise 23h2

### Version number

v1.8.1

**Comment by FedeP14** [comment]
You probably don't have WebView2

**Comment by RyuuseiAkira** [comment]
> You probably don't have WebView2

i have WebView2 runtime v128 on my Windows11 home SL 23h2 and its not running

**Comment by RyuuseiAkira** [comment]
i opened `start.bat` in `C:\Program Files\glzr.io\Zebar\resources` and it works lol

**Comment by lars-berger** [comment]
> i opened `start.bat` in `C:\Program Files\glzr.io\Zebar\resources` and it works lol

`start.bat` has been removed altogether and Zebar can be launched by running the executable normally now 👌 

Also added a note about WebView2 being required to a new faq section in the readme [here](https://github.com/glzr-io/zebar?tab=readme-ov-file#-faq).

LMK if the problem isn't either of these things and we can reopen the issue.

**Comment by Ericosia** [comment]
Hey, 
I have done a clean install of windows today and reinstalled glazewm and zebar, and i have ran into this issue where zebar doesnt even load, i can't open its settings or nothing. I have WebView2 installed and it's still not working.
